services:
    smibo_task_scheduler.run_command:
        class: Smibo\Bundle\TaskSchedulerBundle\Command\TaskSchedulerCommand
        tags:
            - { name: 'console.command', command: 'task-scheduler:run' }
    smibo_task_scheduler.run_task_command:
        class: Smibo\Bundle\TaskSchedulerBundle\Command\TaskSchedulerRunTaskCommand
        tags:
            - { name: 'console.command', command: 'task-scheduler:run-task' }
